/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicaprogramadaarchivos;

import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author fernandafajardo
 */
public class FichaMedica extends javax.swing.JFrame {
    
    private String cedula, nombre, sintoma, diagnostico, tratamiento;    
    
    /**
     * Creates new form FichaMedica
     */
    public FichaMedica() {
        initComponents();
    }
    
    private void agregarPaciente(){
        
            //Capturo los datos de los campos
            nombre = txtNombre.getText();
            cedula = txtCedula.getText();
            sintoma = txtSintoma.getText();
            diagnostico = txtDiagnostico.getText();
            tratamiento = txtTratamiento.getText();

        try{
            try(DataOutputStream dos = new DataOutputStream(new FileOutputStream("pacientes.dat", true))){

                dos.writeUTF(nombre);
                dos.writeUTF(cedula);
                dos.writeUTF(sintoma);
                dos.writeUTF(diagnostico);
                dos.writeUTF(tratamiento);
            }
            JOptionPane.showMessageDialog(null, "Paciente agregado correctamente", "Datos Guardados", JOptionPane.INFORMATION_MESSAGE);
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error al guardar al paciente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void guardarDatos(String datos){
        
        try(DataOutputStream dos = new DataOutputStream(new FileOutputStream("pacientes.dat", true))){
                String lineas[] =  datos.split("\n");
                
                for(int i = 0; i < lineas.length; i+=5){ // Cada registri tiene 4 lineas
                    if(i + 4 < lineas.length){ // asegurar que sean suficientes lineas
                        dos.writeUTF(lineas[i]);
                        dos.writeUTF(lineas[i+1]);
                        dos.writeUTF(lineas[i+2]);
                        dos.writeUTF(lineas[i+3]);
                        dos.writeUTF(lineas[i+4]); 
                    }
                }
                
                dos.writeUTF(nombre);
                dos.writeUTF(cedula);
                dos.writeUTF(sintoma);
                dos.writeUTF(diagnostico);
                dos.writeUTF(tratamiento);

        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error al guardar datos del paciente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    private void consultarNombre() {
        String nombreBuscar = txtNombre.getText();

        try (DataInputStream dis = new DataInputStream(new FileInputStream("paciente.dat"))) {
            boolean encontrado = false;

            while (true) {
                try {
                    String cedula = dis.readUTF();
                    String nombre = dis.readUTF();
                    String sintomas = dis.readUTF();
                    String diagnostico = dis.readUTF();
                    String tratamiento = dis.readUTF();

                    if (nombre.equalsIgnoreCase(nombreBuscar)) {
//                        txtResultado.append("Cédula: " + cedula + "\nNombre: " + nombre + "\nSíntomas: " + sintomas +
//                                            "\nDiagnóstico: " + diagnostico + "\nTratamiento: " + tratamiento + "\n\n");
//                        
                    txtResultado.setText(txtResultado.getText() + "Cédula: " + cedula + "\nNombre: " + nombre + 
                            "\nSíntomas: " + sintomas + "\nDiagnóstico: " + diagnostico + 
                            "\nTratamiento: " + tratamiento + "\n\n");

                        
                        encontrado = true;
                        // break; // Descomentar si solo quieres el primer resultado encontrado.
                    }
                } catch (EOFException e) {
                    break; // Fin del archivo, salimos del bucle
                }
            }

            if (!encontrado) {
                JOptionPane.showMessageDialog(null, "Error, Paciente no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al leer el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSintoma = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnConsultaN = new javax.swing.JButton();
        btnConsultaS = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Cédula");

        jLabel3.setText("Sintoma");

        jLabel4.setText("Diagnostico");

        jLabel5.setText("Tratamiento");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnConsultaN.setText("Consultar por Nombre");
        btnConsultaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaNActionPerformed(evt);
            }
        });

        btnConsultaS.setText("Consultar por Sintomas");
        btnConsultaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtNombre))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSintoma, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(txtDiagnostico)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultaS)
                            .addComponent(btnConsultaN)
                            .addComponent(btnAgregar))
                        .addGap(85, 85, 85)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultaN)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultaS))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregarPaciente();
        txtNombre.setText(" ");
        txtCedula.setText(" ");
        txtSintoma.setText(" ");
        txtDiagnostico.setText(" ");
        txtTratamiento.setText(" ");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnConsultaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaNActionPerformed
        // TODO add your handling code here:
        consultarNombre();
    }//GEN-LAST:event_btnConsultaNActionPerformed

    private void btnConsultaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultaN;
    private javax.swing.JButton btnConsultaS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtResultado;
    private javax.swing.JTextField txtSintoma;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
